---
--- Generated by Luanalysis
--- Created by fangjinuo.
--- DateTime: 2020/9/19 18:07
--- unlock(key, expectedValue, force)
--- @return boolean

local value = redis.call("get", KEYS[1])
if ARGS[2] then
    redis.call("del", KEYS[1])
    return true
else
    if value == ARGS[1] then
        redis.call("del", KEYS[1])
        return true
    else
        return false
    end
end
